import { WebSocketServer } from "ws";
import { trains } from "./data.js";
import { predictEta } from "./prediction.js";
import { LivePosition, TrainSnapshot } from "./types.js";
const positions = new Map<string, LivePosition>();
const previousDelays = new Map<string, number>();
trains.forEach((train, index) => { const first = train.route[0]; positions.set(train.number, { trainNumber: train.number, lat: first.lat, lon: first.lon, speed: 74 + index * 4, status: "running", delayMinutes: 5 + index * 3, lastReportedStation: first.name, nextStation: train.route[1].code, progress: 0.2 + index * 0.05, updatedAt: new Date().toISOString() }); previousDelays.set(train.number, 5 + index * 3); });
const snapshotFor = (trainNumber: string): TrainSnapshot => { const train = trains.find((item) => item.number === trainNumber)!; const position = positions.get(trainNumber)!; return { train, position, prediction: predictEta(train, position, previousDelays.get(trainNumber)) }; };
export function getSnapshots() { return trains.map((train) => snapshotFor(train.number)); }
export function startSimulator(wss: WebSocketServer) { setInterval(() => { trains.forEach((train, index) => { const current = positions.get(train.number)!; previousDelays.set(train.number, current.delayMinutes); const nextProgress = current.progress + 0.018 + index * 0.002; const nextStationIndex = train.route.findIndex((station) => station.code === current.nextStation); const sectionDone = nextProgress >= 1; const stationIndex = sectionDone ? Math.min(train.route.length - 1, nextStationIndex + 1) : nextStationIndex; const station = train.route[stationIndex]; const following = train.route[Math.min(train.route.length - 1, stationIndex + 1)]; const delayChange = Math.random() > 0.72 ? (Math.random() > 0.55 ? 1 : -1) : 0; positions.set(train.number, { ...current, lat: sectionDone ? station.lat : current.lat + (station.lat - current.lat) * 0.018, lon: sectionDone ? station.lon : current.lon + (station.lon - current.lon) * 0.018, speed: Math.max(42, Math.min(112, current.speed + (Math.random() - 0.5) * 8)), delayMinutes: Math.max(0, current.delayMinutes + delayChange), lastReportedStation: sectionDone ? station.name : current.lastReportedStation, nextStation: following.code, progress: sectionDone ? 0 : nextProgress, status: stationIndex === train.route.length - 1 ? "terminated" : "running", updatedAt: new Date().toISOString() }); }); const message = JSON.stringify({ type: "snapshot", payload: getSnapshots() }); wss.clients.forEach((client) => { if (client.readyState === 1) client.send(message); }); }, 4000); }